os: osx

git:
  depth: 5

env:
  global:
    - "FTP_USER=upload@sagecommons.org"
    - "FTP_PASSWORD=nJ5DR4tXepEgiOsXpf4omw=="
  matrix:
    - NODE_VERSION="0.10.36"
    - NODE_VERSION="0.12.7"
    - NODE_VERSION="4.0.0"

before_install:
  - brew update
  - brew install ffmpeg --with-libvpx --with-libvorbis

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node -v
  - npm -v 
  - npm install

after_success:
    "tar czvf node-demux_mac_$TRAVIS_NODE_VERSION.tar.gz ."
    "curl --ftp-create-dirs -T node-demux_mac_$TRAVIS_NODE_VERSION.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://sagecommons.org/node-demux_mac_$TRAVIS_NODE_VERSION.tar.gz"

