os: osx

language: objective-c

git:
  depth: 5

env:
  global:
    - secure: "KL51WoF2eBTPuPSnUp/GDmift25LqsntrHXNI9vtDWcvPd7lSTeHdNsH7po/VU6PFFkLIVdZcw+fxgmvSZDY8n379RkL7NOaLoHo1X3EZUQYioA/ROZz2eZ42jiPPsxZTdbBkpkGgkRqU9YcnWVWzqaKNqX82cqF/UQ197ZlXoXWhF0WLMNvdkliTz2Q46TZXLW5/V8+mVRYxU8bplwCHi9SZIUqXtE5L/iz6HgZKGGwGeCRZxulAiUUYgF89sj34iP0Ia9dpG1PonLUZNl5nyxex9dQ2aDFebVnTO7Z0taSurJNBMFL4ptxE9G5puV7IUCQFaC6Wc/TOuGGaZToOxJDW6NbnDcaipPTad85JpGNMBIV0sCQQ89pBSGC/tODAsrJy8F6wdOej7WqbHVlbOsMdhKi3HAQZJZp7UdQfJwdq0TXsobqfImgD8nd1zdgMBmdPsyc6aA9I20i8+l/okfAphf5rTumpmCZru7XSAZFEINF5skHtqQm5JuGV5JDtQHa63Bf/pjYIYTgw1gFFoJG2tYFUM3nMNPswzRYuKBvllERjH1FwJ5UNcyP8KZVdMGLGFSt6cge92gGrfM7Y3jduUnDNV3uTP9TJ4dcPN5/MTt8iOk6yJGrYrQ4Qn5QhMOqmFJuM4YVW50gmUQw5XZmFfpolV2NYafKIpOEU1U="
  matrix:
    - NODE_VERSION="0.10.40"
    - NODE_VERSION="0.12.7"
    - NODE_VERSION="4.2.3"
    - NODE_VERSION="5.1.0"

before_install:
  - brew update
  - brew install ffmpeg --with-libvpx --with-libvorbis

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node -v
  - npm -v
  - npm install

script:
  - mkdir /Users/travis/build/tmarrinan/Build
  - cd ..
  - tar czf /Users/travis/build/tmarrinan/Build/node-demux_mac_${NODE_VERSION}.tar.gz node-demux
  - cd node-demux
  - mv /Users/travis/build/tmarrinan/Build/node-demux_mac_${NODE_VERSION}.tar.gz .
  - curl -O https://bitbucket.org/tmarrinan/binary-modules/raw/master/bitbucket_upload.js
  - node bitbucket_upload.js tmarrinan $BITBUCKET_PASSWORD tmarrinan/binary-modules node-demux_mac_${NODE_VERSION}.tar.gz
  - ls -a

