os: osx

language: objective-c

env:
  matrix:
    - NODE_VERSION="0.10.36"
    - NODE_VERSION="0.12.7"
    - NODE_VERSION="4.0.0"

before_install:
  - brew update
  - brew install ffmpeg --with-libvpx --with-libvorbis

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node -v
  - npm -v
  - npm install

script:
  - mkdir /Users/travis/build/tmarrinan/Build
  - tar czf /Users/travis/build/tmarrinan/Build/node-demux_mac_${NODE_VERSION}.tar.gz .
  - mv /Users/travis/build/tmarrinan/Build/node-demux_mac_${NODE_VERSION}.tar.gz .
  - ls -a
  - ls -a /Users/travis/build/tmarrinan/Build

deploy:
  provider: releases
  api_key:
    secure: RaPCJDCKkk/ff5tvmBG0TcKFMTWsU7ENFPUq6r+FnjYKvmef+PXtIs6YoraywdYj13BMAbssIk2671mpmX1VPjD/ub0+pgndL1zetidaSmZtL79c8/Y+KrbqG3lSxg9ONjOUt9E2w8fRKWTqrAe8dDnSHd4quVCOHmbPr2xMjBi71JPOan7iv27Pde9ISzwNFiQ/5iIIYm8WRjf26T0AZ07ydR1jEKzV+VH728LzUXKz0p0xzElqaQp/uE6kCMmr6KUif3H+Hq/4S5borDvhvHHSWyu6GSibWD47BwtEoKJPY1bb1E15h5ETW6hOKqaJ8l4Y3GC3v01f0ly4cPeCB9o5kry61bmNqPLfnb4j8/syKUEH5q7Bih0K7xfd8/b+xgmfw6noOOWGSYfhkM5gewqnXq6Jd+HbaCL8OpOiMTyIn72Iz+N9Zv8z7wEX5qsWQMCqzaIoQNnTBWk6p3lGF0jcYJ9fo6M/VSFqRp0EH8KaF6+5QZZ81ARQoNn1/vfxrvTINtcEjEsxWaiV+OuG2/uzLh7NCzWWTlwBQ3Urme9egD8IaaixpZZ59YUgiFZ8OklRXS4lFKnayKQUU1aRM+ekOwJDDScKGBlT26R35OY60b488mzhbWlBP+Dnz+SzJ7XBarXvjBgPoeE5C6zy2XRVYhinrJIe5CV5B9FMCl4=
  file: node-demux-mac_$NODE_VERSION.tar.gz
  on:
    repo: tmarrinan/node-demux
