os: osx

language: objective-c

env:
  global:
    - "FTP_USER=upload@sagecommons.org"
    - secure: "g5jlEjKUAStB25lyMCTJCCzWqwvLR4Y+NC9lQ9/MBxJ9iuTdWdoOwqk5dp785YsKP550TUjHTkvvh/K1EpBe/RKiruWWA6/hMZq5jT9a46oJ+gdG4g5Gb5udOBDo1umbnc8FeMW5mtolgcJqfV+2ViyfU+yiWhdFQyUFULFdIg90yBQrPZoDgd5wELFkE6IfgH9jbpbbruvqYgVGMb8j9Dz4ClPmZEYeMIbXSP5eaVc4y1+K7HMBkWbAV2u2RjLWgIjcbdFLXjocmGpASJ30dxqhT/C4Gj3s7xArQkihZytMI/wJHOKhjzGxOlBpBzjtRJsQt+As+gRacoqGWAaRIOGe/c4OnSsmkLIu1DwdemeLTRSxVI8qi/Cd9p0w6gWie71aOvp/70Q3f3FZyfAFIhj8EnD/317FfgrIkj75Uk7QyekfCv4azQEiU9FU3gT+60zPmd29KY9undZFGpRrPr10YuAhxB48qRQg53YJ10nSI9FhJu6jYWsFpujuXaxKT9UWTUa2MwtLT4pcKgQPAIrtr4Ozbv7OIltVqFXuACtQJXcLNkmUAiSUgBi2FzncQVrsofCIeEzonKcTdZps56FP/WK2bwmGAZk9R/r3Y9YIN7RCmY4PGJwpm+Ub2imKPK+kNahmeCTW5N+6dFYGgrqLNLFBE889woymSUCcKjw="
  matrix:
    - NODE_VERSION="0.10.36"
    - NODE_VERSION="0.12.7"
    - NODE_VERSION="4.0.0"

before_install:
  - brew update
  - brew install ffmpeg --with-libvpx --with-libvorbis

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node -v
  - npm -v 
  - npm install

after_success:
    "tar czvf node-demux_mac_$NODE_VERSION.tar.gz ."
    "curl --ftp-create-dirs -T node-demux_mac_$NODE_VERSION.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://sagecommons.org/node-demux_mac_$NODE_VERSION.tar.gz"

