os: osx

language: objective-c

env:
  global:
    - "FTP_USER=upload@sagecommons.org"
    - secure: "iYSHQw2b2M6JTQvCtdidz0t9NjN7yhf82ILifzBTrq8KJBfqnKNkGxTRuaztML5zbtV4bXhhSQLBcA1VX1wGJzNU60jlsAzWVNrReqWJEwip6wsyFRUu6xRarpi38FwNt9RAReRPsAPHpyBJyEzifDgd4ZnV9I9GMgLJ/DKakFeBQKM/1bK+iq4ZrPHeFTW7hJKcQGKW8Gt7xlm2d1griDJaXy5XVK71Zk3WJNCekWqvRDvQzF/aj+3sqZ7N+BAQd6qRL+KuweuYZHqJJ/855HlPMZyIklx+YP1GUgMYvYOk1uV2q4zzIxeS2LHmArzeiD1jFVsGCnP69eBqYlyei59y2oCmy75fLNfycCtZrDe2Wo/v0UeCjsDor/r92NinlmjHYjA0oS2iBuEDRNY4UPNhHUU1zNHIxD62OWCwWZVBzMk5M33jUP4xTrCp+AXqhmB7L4g/M00uBAaIXXDAY3NPdWHw77tWDVpuDpCd4xQpjLIG48meWYH3qkweOhjvz6N7tU1s481fY8s0rVTKwmLvuRMJrfW8S067n9aK96Fr8N16/3s/1lE7GnyVtwa+AHZe2dvbB1sneATO++VnbjkpW5tfLbRtvY3owUL33bQAhq76kiMcH1uj5/yJ1wBLrp3vKT+sPj0NrZRCnmusK/PHfIVNovGIYFTdHXlnyWQ="
  matrix:
    - NODE_VERSION="0.10.36"
    - NODE_VERSION="0.12.7"
    - NODE_VERSION="4.0.0"

before_install:
  - brew update
  - brew install ffmpeg --with-libvpx --with-libvorbis

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node -v
  - npm -v 
  - npm install

script:
  - tar czf node-demux_mac_${NODE_VERSION}.tar.gz .
  - ls
  - echo $FTP_USER
  - echo $FTP_PASSWORD

after_success:
    "curl --ftp-create-dirs -T node-demux_mac_${NODE_VERSION}.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://sagecommons.org/node-demux_mac_${NODE_VERSION}.tar.gz"

