version: 1.0.{build}

branches:
  only:
  - master

configuration: Release
platform: x64
clone_depth: 5

init:
- curl -LsSO http://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-20150916-git-cbbd906-win64-dev.7z
- 7z x ffmpeg-20150916-git-cbbd906-win64-dev.7z -o.
- mkdir C:\Dev\
- mkdir C:\Dev\ffmpeg-win64-dev
- move ffmpeg-20150916-git-cbbd906-win64-dev\lib C:\Dev\ffmpeg-win64-dev
- move ffmpeg-20150916-git-cbbd906-win64-dev\include C:\Dev\ffmpeg-win64-dev
- del /Q *.7z
- rmdir /Q /S ffmpeg-20150916-git-cbbd906-win64-dev
- dir C:\Dev
- dir C:\Dev\ffmpeg-win64-dev\include
- dir C:\Dev\ffmpeg-win64-dev\lib

environment:
  global:
  - my_variable:
      secure: /975A5J1RV6XLgHNZnUkcaSwNYlEjiZaDECRyXFaEQnUyYOKWHizDCmchvNd8UaU
  matrix:
  - nodejs_version: 0.10.36
  - nodejs_version: 0.12.7
  - nodejs_version: 4.0.0

install:
- ps: >-
    Install-Product node $env:nodejs_version x64

    npm -v

    node -v

    npm install --production --msvs_version=2013

build:
  parallel: true
  verbosity: minimal

after_build:
- curl -LsSO http://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-20150916-git-cbbd906-win64-shared.7z
- 7z x ffmpeg-20150916-git-cbbd906-win64-shared.7z -o.
- move ffmpeg-20150916-git-cbbd906-win64-shared\bin\* build\Release
- rmdir /Q /S ffmpeg-20150916-git-cbbd906-win64-shared
- del /Q *.7z
- rmdir /Q /S .git
- mkdir C:\Build\
- 7z a -ttar C:\Build\node-demux_win_%nodejs_version%.tar C:\projects\node-demux\
- 7z a -tgzip C:\Build\node-demux_win_%nodejs_version%.tar.gz C:\Build\node-demux_win_%nodejs_version%.tar
- move C:\Build\node-demux_win_%nodejs_version%.tar.gz C:\projects\node-demux

test: off

artifacts:
- path: node-demux_win_$(nodejs_version).tar.gz
  name: node-demux-win64

deploy:
- provider: FTP
  host: ftp.sagecommons.org
  protocol: ftp
  username: upload@sagecommons.org
  password:
    secure: nJ5DR4tXepEgiOsXpf4omw==
  folder: /
  artifact: node-demux-win64

after_deploy:
- dir

notifications:
- provider: Slack
  auth_token:
    secure: zWPzLLrh/2HV3lXJd9q5XK+m2D1zn/bWBIQOzjQ2QkFSFL3ijB839EMqTRUrYZeA
  channel: appveyor
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
